version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-11.13
    steps:
      - checkout
      - restore-cache:
          keys:
            - stack-work-{{checksum "stack.yaml" }}-\
                       {{checksum "package.yaml" }}
      - run: stack setup
      - run: stack build
      - run: stack test
      - save_cache:
          key: stack-work-{{ checksum "stack.yaml" }}-\
                          {{ checksum "package.yaml" }}
          paths:
            - ".stack-work"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
